import { DEFAULT_RESOLUTION, GAME_RESOLUTION } from "./constants";

const factorResolution = {
  fw: GAME_RESOLUTION.width / DEFAULT_RESOLUTION.width,
  fh: GAME_RESOLUTION.height / DEFAULT_RESOLUTION.height,
};

export const configObjects = {
  lilySpawner: {
    startPos: {
      x: 0,
      y: 600 * factorResolution.fh,
    },
    rangeX: {
      min: 186 * factorResolution.fw,
      max: 650 * factorResolution.fw,
    },
    texture: "lily",
    frame: "wave/0001.png",
    animation: {
      prefixWave: "wave/",
      prefixSolved: "solved/",
      prefixLine: "line/",
      suffix: ".png",
    },
    divisionSign: {
      x: 0,
      y: 0,
      texture: "divisionSign",
      origin: { x: 0.5, y: 0.5 },
      scale: { x: 1.2 * factorResolution.fw, y: 1.2 * factorResolution.fh },
    },
    textObject: {
      x: 20 * factorResolution.fw,
      y: 0,
      origin: { x: 1.0, y: 0.5 },
      scale: { x: 1.2 * factorResolution.fw, y: 1.2 * factorResolution.fh },
    },
    textObjectForSign: {
      origin: { x: 0.0, y: 0.5 },
    },
    rt: {
      x: 400 * factorResolution.fw,
      y: 300 * factorResolution.fh,
      width: 128 * factorResolution.fw,
      height: 128 * factorResolution.fh,
      textObject: {
        x: (64 + 23) * factorResolution.fw,
        y: 64 * factorResolution.fh,
      },
      textObjectForSign: {
        x: (64 - 37) * factorResolution.fw,
        y: 64 * factorResolution.fh,
      },
      divisionSign: {
        x: (64 - 28) * factorResolution.fw,
        y: 65 * factorResolution.fh,
      },
    },
  },
  soundControl: {
    x: 20 * factorResolution.fw,
    y: 20 * factorResolution.fh,
    texture: "gui",
    frameOn: "sound_on.svg",
    frameOff: "sound_off_light.svg",
  },
  pauseControl: {
    x: 752 * factorResolution.fw,
    y: 24 * factorResolution.fh,
    origin: { x: 0.0, y: 0.0 },
    texture: "gui",
    frame: "pause.svg",
    depth: 1,
  },
  leftSand: {
    x: 0,
    y: 300 * factorResolution.fh,
    texture: "background",
    frame: "sand_left_side.png",
    origin: { x: 0.0, y: 0.5 },
  },
  rightSand: {
    x: 800 * factorResolution.fw,
    y: 300 * factorResolution.fh,
    texture: "background",
    frame: "sand_right_side.png",
    origin: { x: 1.0, y: 0.5 },
  },
  scoreText: {
    label: {
      text: "Score",
      x: 60 * factorResolution.fw,
      y: 335 * factorResolution.fh,
      origin: { x: 0.5, y: 0.5 },
      depth: 1,
    },
    plusPts: {
      x: 60 * factorResolution.fw,
      y: 395 * factorResolution.fh,
      origin: { x: 0.5, y: 0.5 },
      depth: 1,
      value: 100,
    },
    valueText: {
      x: 60 * factorResolution.fw,
      y: 355 * factorResolution.fh,
      origin: { x: 0.5, y: 0.5 },
    },
    textDistance: {
      x: 0,
      y: 60 * factorResolution.fw,
    },
  },
  boat: {
    x: 56 * factorResolution.fw,
    y: 347 * factorResolution.fh,
    texture: "actors",
    frame: "boat.png",
    angle: -5.5,
  },
  bridge: {
    x: 400 * factorResolution.fw,
    y: 600 * factorResolution.fh,
    origin: { x: 0.5, y: 1.0 },
    texture: "actors",
    frame: "bridge.png",
    depth: 1,
  },
  rightStones: {
    x: 800 * factorResolution.fw,
    y: 483 * factorResolution.fh,
    origin: { x: 1.0, y: 0.0 },
    texture: "actors",
    frame: "leaves_stones_right.png",
    depth: 1,
  },
  leftStones: {
    x: 0,
    y: 600 * factorResolution.fh,
    origin: { x: 0.0, y: 1.0 },
    texture: "actors",
    frame: "leaves_stones_left.png",
    depth: 1,
  },
  heartsGroupContainer: {
    name: "heartsGroup",
    x: 765 * factorResolution.fw,
    y: 355 * factorResolution.fh,
    depth: 1.0,
    distance: 30 * factorResolution.fh,
    texture: "gui",
    frame: "filled_heart.svg",
    frameEmpty: "empty_heart.svg",
    origin: { x: 0.5, y: 0.5 },
    tweenConfig: {
      scale: { x: 1.2 * factorResolution.fw, y: 1.2 * factorResolution.fh },
      duration: 170,
      ease: "Quad.easeInOut",
    },
  },
  containerInputGUI: {
    name: "containerInputGUI",
    x: 0,
    y: 477 * factorResolution.fh,
    depth: 1.0,
    inputField: {
      name: "inputField",
      x: 0,
      y: 0,
      texture: "inputField",
      frame: "0001.png",
      wrongFrame: "0002.png",
      origin: { x: 0.5, y: 0.5 },
      size: { x: 100, y: 100 },
      depth: 1.0,
      length: 5,
    },
    resetButton: {
      name: "resetButton",
      x: 0,
      y: 0,
      texture: "gui",
      frame: "reset_btn.png",
      origin: { x: 0.5, y: 0.5 },
      distance: 40 * factorResolution.fw,
      size: { x: 100, y: 100 },
      depth: 1.0,
    },
    setButton: {
      name: "setButton",
      x: 0,
      y: 0,
      texture: "gui",
      frame: "submit_btn.png",
      origin: { x: 0.5, y: 0.5 },
      distance: 40 * factorResolution.fh,
      size: { x: 100, y: 100 },
      depth: 1.0,
    },
  },
  logic: {
    lineSpawn: 200 * factorResolution.fh,
  },
  containerDigitalGUI: {
    name: "containerDigitalGUI",
    x: 316 * factorResolution.fw,
    y: 547 * factorResolution.fh,
    depth: 1.0,
    digitalButton: {
      name: "digitalButton",
      x: 0,
      y: 0,
      texture: "gui",
      frame: "digit_button.png",
      origin: { x: 0.5, y: 0.5 },
      distance: 70 * factorResolution.fw,
      size: { x: 100, y: 100 },
      depth: 1.0,
    },
  },
  waterShader: {
    name: "cartoonWaterShader",
    iChannel0: "cartoonWater",
    iChannel1: "noiseWater",
    iChannel2: "noise",
  },
  menuWaterLily: {
    x: 770 * factorResolution.fw,
    y: 670 * factorResolution.fh,
    texture: "actors",
    frame: "water_lily.png",
    origin: { x: 0.0, y: 0.0 },
    angle: -135.0,
    setFlipY: true,
  },
  soundsName: {
    background: "background",
    gameOver: "gameOver",
    wrong: "wrong",
    missed: "missed",
    solved: "solved",
  },
  menuButton: {
    x: 0.0,
    y: 0.0,
    texture: "buttonBackground",
    defaultFrame: "default.png",
    hoverFrame: "hover.png",
    pressedFrame: "pressed.png",
  },
  buttonContainer: {
    buttonDistance: {
      x: 0,
      y: 40 * factorResolution.fh,
    },
  },
  rulesTextArea: {
    name: "textArea",
    x: 100 * factorResolution.fw,
    y: 75 * factorResolution.fh,
    text: {
      value:
        "Phasellus tempor velit tellus, tempus facilisis sem placerat et. Maecenas et risus in tortor bibendum laoreet. Vestibulum vel augue nec erat dignissim ullamcorper vel vel dui. Fusce rutrum libero ornare dolor luctus, sit amet eleifend elit rutrum. \n" +
        "\n" +
        "Sed tincidunt urna eu leo gravida hendrerit. Nam imperdiet fermentum felis, venenatis mattis justo ultrices vitae. Maecenas odio orci, vehicula in egestas a, ultrices quis risus. Etiam posuere rhoncus erat, in suscipit erat dignissim at. \n" +
        "\n" +
        "Nam imperdiet fermentum felis, venenatis mattis justo ultrices vitae. Maecenas odio orci, vehicula in egestas a, ultrices quis risus. Etiam posuere rhoncus erat, in suscipit erat dignissim at.",
      x: 44 * factorResolution.fw,
      y: 32 * factorResolution.fh,
    },
    background: {
      x: 0.0,
      y: 0.0,
      width: 600 * factorResolution.fw,
      height: 350 * factorResolution.fh,
      color: 0xffffff,
      alpha: 1.0,
      borderRadius: 8 * factorResolution.fw,
    },
  },
  countDown: {
    count: 3,
    x: 0.0,
    y: 0.0,
    scale: {
      x: 0.4 * factorResolution.fw,
      y: 0.4 * factorResolution.fh,
    },
    scaleTween: {
      x: `${factorResolution.fw}`,
      y: `${factorResolution.fh}`,
    },
    ease: "Quad.easeInOut",
    origin: { x: 0.5, y: 0.5 },
    startedDelta: 0.75,
    alphaDuration: 1000,
    scaleDuration: 500,
  },
};
